# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/adamlind/Development/janitor_shooter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/adamlind/Development/janitor_shooter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/adamlind/Development/janitor_shooter/CMakeFiles /Users/adamlind/Development/janitor_shooter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/adamlind/Development/janitor_shooter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shooter

# Build rule for target.
Shooter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Shooter
.PHONY : Shooter

# fast build rule for target.
Shooter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/build
.PHONY : Shooter/fast

src/Character.o: src/Character.cpp.o
.PHONY : src/Character.o

# target to build an object file
src/Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Character.cpp.o
.PHONY : src/Character.cpp.o

src/Character.i: src/Character.cpp.i
.PHONY : src/Character.i

# target to preprocess a source file
src/Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Character.cpp.i
.PHONY : src/Character.cpp.i

src/Character.s: src/Character.cpp.s
.PHONY : src/Character.s

# target to generate assembly for a file
src/Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Character.cpp.s
.PHONY : src/Character.cpp.s

src/Collision.o: src/Collision.cpp.o
.PHONY : src/Collision.o

# target to build an object file
src/Collision.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Collision.cpp.o
.PHONY : src/Collision.cpp.o

src/Collision.i: src/Collision.cpp.i
.PHONY : src/Collision.i

# target to preprocess a source file
src/Collision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Collision.cpp.i
.PHONY : src/Collision.cpp.i

src/Collision.s: src/Collision.cpp.s
.PHONY : src/Collision.s

# target to generate assembly for a file
src/Collision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Collision.cpp.s
.PHONY : src/Collision.cpp.s

src/Combat.o: src/Combat.cpp.o
.PHONY : src/Combat.o

# target to build an object file
src/Combat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Combat.cpp.o
.PHONY : src/Combat.cpp.o

src/Combat.i: src/Combat.cpp.i
.PHONY : src/Combat.i

# target to preprocess a source file
src/Combat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Combat.cpp.i
.PHONY : src/Combat.cpp.i

src/Combat.s: src/Combat.cpp.s
.PHONY : src/Combat.s

# target to generate assembly for a file
src/Combat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Combat.cpp.s
.PHONY : src/Combat.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameObject.o: src/GameObject.cpp.o
.PHONY : src/GameObject.o

# target to build an object file
src/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/GameObject.cpp.o
.PHONY : src/GameObject.cpp.o

src/GameObject.i: src/GameObject.cpp.i
.PHONY : src/GameObject.i

# target to preprocess a source file
src/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/GameObject.cpp.i
.PHONY : src/GameObject.cpp.i

src/GameObject.s: src/GameObject.cpp.s
.PHONY : src/GameObject.s

# target to generate assembly for a file
src/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/GameObject.cpp.s
.PHONY : src/GameObject.cpp.s

src/TextureManager.o: src/TextureManager.cpp.o
.PHONY : src/TextureManager.o

# target to build an object file
src/TextureManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/TextureManager.cpp.o
.PHONY : src/TextureManager.cpp.o

src/TextureManager.i: src/TextureManager.cpp.i
.PHONY : src/TextureManager.i

# target to preprocess a source file
src/TextureManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/TextureManager.cpp.i
.PHONY : src/TextureManager.cpp.i

src/TextureManager.s: src/TextureManager.cpp.s
.PHONY : src/TextureManager.s

# target to generate assembly for a file
src/TextureManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/TextureManager.cpp.s
.PHONY : src/TextureManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shooter.dir/build.make CMakeFiles/Shooter.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Shooter"
	@echo "... src/Character.o"
	@echo "... src/Character.i"
	@echo "... src/Character.s"
	@echo "... src/Collision.o"
	@echo "... src/Collision.i"
	@echo "... src/Collision.s"
	@echo "... src/Combat.o"
	@echo "... src/Combat.i"
	@echo "... src/Combat.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameObject.o"
	@echo "... src/GameObject.i"
	@echo "... src/GameObject.s"
	@echo "... src/TextureManager.o"
	@echo "... src/TextureManager.i"
	@echo "... src/TextureManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

