name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SDL2
        run: |
          brew install sdl2
          brew install sdl2_image
    
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

