name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SDL2
        run: |
          brew install sdl2
          brew install sdl2_image
    
      - name: Build
        run: |
          cmake .
          make

      - name: Export artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: bin/
