name: Build Windows
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          cmake .
          make

      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: Binaries
          path: bin/
